<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>telemetry_tracker</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="telemetry-tracker.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="telemetry-tracker.Tests\**\*.cs" />
    <EmbeddedResource Remove="telemetry-tracker.Tests\**\*" />
    <None Remove="telemetry-tracker.Tests\**\*" />
  </ItemGroup>

</Project>
