[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string]$Name,
    [string]$BaseBranch = "main",
    [string]$BranchName,
    [string]$WorktreeRoot,
    [switch]$SkipRestore
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Get-RepositoryRoot {
    return (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
}

function ConvertTo-Slug {
    param(
        [Parameter(Mandatory)]
        [string]$Value
    )

    $slug = $Value.ToLowerInvariant()
    $slug = [Regex]::Replace($slug, "[^a-z0-9]+", "-")
    $slug = $slug.Trim("-")

    if ([string]::IsNullOrWhiteSpace($slug)) {
        throw "Unable to derive a branch-safe slug from '$Value'."
    }

    return $slug
}

function Get-DefaultWorktreeRoot {
    param(
        [Parameter(Mandatory)]
        [string]$RepositoryRoot
    )

    $parent = Split-Path $RepositoryRoot -Parent
    return Join-Path $parent "telemetry-tracker-worktrees"
}

$repoRoot = Get-RepositoryRoot

if ([string]::IsNullOrWhiteSpace($BranchName)) {
    $BranchName = "Spike/$(ConvertTo-Slug -Value $Name)"
}

if ([string]::IsNullOrWhiteSpace($WorktreeRoot)) {
    $WorktreeRoot = Get-DefaultWorktreeRoot -RepositoryRoot $repoRoot
}

$resolvedWorktreeRoot = [System.IO.Path]::GetFullPath($WorktreeRoot)
$worktreePath = Join-Path $resolvedWorktreeRoot $Name

if (Test-Path -LiteralPath $worktreePath) {
    throw "Target worktree path already exists: $worktreePath"
}

New-Item -ItemType Directory -Path $resolvedWorktreeRoot -Force | Out-Null

Push-Location $repoRoot

try {
    $existingBranch = git branch --list --format="%(refname:short)" -- $BranchName
    if ($LASTEXITCODE -ne 0) {
        throw "Unable to inspect existing branches."
    }

    if ([string]::IsNullOrWhiteSpace(($existingBranch | Out-String).Trim())) {
        & git worktree add -b $BranchName $worktreePath $BaseBranch
    }
    else {
        & git worktree add $worktreePath $BranchName
    }

    if ($LASTEXITCODE -ne 0) {
        throw "git worktree add failed."
    }
}
finally {
    Pop-Location
}

$agentEnvPath = Join-Path $worktreePath ".env.agent"
$agentEnvLines = @(
    "# Generated by scripts/New-AgentWorkspace.ps1",
    "DOTNET_ENVIRONMENT=Development",
    "TELEMETRY_TRACKER_WORKSPACE_NAME=$Name",
    "TELEMETRY_TRACKER_BRANCH_NAME=$BranchName"
)
[System.IO.File]::WriteAllLines($agentEnvPath, $agentEnvLines)

$metadataPath = Join-Path $worktreePath ".agent-workspace.json"
$metadata = [ordered]@{
    name = $Name
    branchName = $BranchName
    baseBranch = $BaseBranch
    createdUtc = (Get-Date).ToUniversalTime().ToString("o")
}
$metadata | ConvertTo-Json | Set-Content -LiteralPath $metadataPath

$sourceEnvPath = Join-Path $repoRoot ".env"
$targetEnvPath = Join-Path $worktreePath ".env"
if ((Test-Path -LiteralPath $sourceEnvPath) -and -not (Test-Path -LiteralPath $targetEnvPath)) {
    Copy-Item -LiteralPath $sourceEnvPath -Destination $targetEnvPath
}

if (-not $SkipRestore) {
    Push-Location $worktreePath
    try {
        & dotnet restore telemetry-tracker.csproj
        if ($LASTEXITCODE -ne 0) {
            throw "dotnet restore failed for the new workspace."
        }
    }
    finally {
        Pop-Location
    }
}

Write-Host ("Created worktree: {0}" -f $worktreePath)
Write-Host ("Branch: {0}" -f $BranchName)
