[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string]$Name,
    [string]$BaseBranch = "main",
    [string]$BranchName,
    [string]$WorktreeRoot,
    [int]$HttpPort,
    [int]$HttpsPort,
    [switch]$SkipRestore
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Get-RepositoryRoot {
    return (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
}

function ConvertTo-Slug {
    param(
        [Parameter(Mandatory)]
        [string]$Value
    )

    $slug = $Value.ToLowerInvariant()
    $slug = [Regex]::Replace($slug, "[^a-z0-9]+", "-")
    $slug = $slug.Trim("-")

    if ([string]::IsNullOrWhiteSpace($slug)) {
        throw "Unable to derive a branch-safe slug from '$Value'."
    }

    return $slug
}

function Get-DefaultWorktreeRoot {
    param(
        [Parameter(Mandatory)]
        [string]$RepositoryRoot
    )

    $parent = Split-Path $RepositoryRoot -Parent
    return Join-Path $parent "telemetry-tracker-worktrees"
}

function Get-ExistingPorts {
    param(
        [Parameter(Mandatory)]
        [string]$RepositoryRoot,
        [Parameter(Mandatory)]
        [string]$ResolvedWorktreeRoot
    )

    $ports = New-Object System.Collections.Generic.HashSet[int]
    $metadataFiles = @()

    $currentMetadataPath = Join-Path $RepositoryRoot ".agent-workspace.json"
    if (Test-Path -LiteralPath $currentMetadataPath) {
        $metadataFiles += $currentMetadataPath
    }

    if (Test-Path -LiteralPath $ResolvedWorktreeRoot) {
        $metadataFiles += Get-ChildItem -Path $ResolvedWorktreeRoot -Recurse -File -Filter ".agent-workspace.json" | Select-Object -ExpandProperty FullName
    }

    foreach ($file in $metadataFiles) {
        try {
            $metadata = Get-Content -LiteralPath $file -Raw | ConvertFrom-Json
            if ($metadata.httpPort) {
                [void]$ports.Add([int]$metadata.httpPort)
            }

            if ($metadata.httpsPort) {
                [void]$ports.Add([int]$metadata.httpsPort)
            }
        }
        catch {
            Write-Warning ("Skipping unreadable workspace metadata file: {0}" -f $file)
        }
    }

    return $ports
}

function Get-NextAvailablePorts {
    param(
        [Parameter(Mandatory)]
        [System.Collections.Generic.HashSet[int]]$UsedPorts,
        [int]$StartingHttpPort = 5227,
        [int]$StartingHttpsPort = 7022
    )

    $http = $StartingHttpPort
    $https = $StartingHttpsPort

    while ($UsedPorts.Contains($http) -or $UsedPorts.Contains($https)) {
        $http++
        $https++
    }

    return @{
        Http = $http
        Https = $https
    }
}

$repoRoot = Get-RepositoryRoot

if ([string]::IsNullOrWhiteSpace($BranchName)) {
    $BranchName = "Spike/$(ConvertTo-Slug -Value $Name)"
}

if ([string]::IsNullOrWhiteSpace($WorktreeRoot)) {
    $WorktreeRoot = Get-DefaultWorktreeRoot -RepositoryRoot $repoRoot
}

$resolvedWorktreeRoot = [System.IO.Path]::GetFullPath($WorktreeRoot)
$worktreePath = Join-Path $resolvedWorktreeRoot $Name

if (Test-Path -LiteralPath $worktreePath) {
    throw "Target worktree path already exists: $worktreePath"
}

$usedPorts = Get-ExistingPorts -RepositoryRoot $repoRoot -ResolvedWorktreeRoot $resolvedWorktreeRoot
$nextPorts = Get-NextAvailablePorts -UsedPorts $usedPorts

if ($HttpPort -le 0) {
    $HttpPort = $nextPorts.Http
}

if ($HttpsPort -le 0) {
    $HttpsPort = $nextPorts.Https
}

New-Item -ItemType Directory -Path $resolvedWorktreeRoot -Force | Out-Null

Push-Location $repoRoot

try {
    $existingBranch = git branch --list --format="%(refname:short)" -- $BranchName
    if ($LASTEXITCODE -ne 0) {
        throw "Unable to inspect existing branches."
    }

    if ([string]::IsNullOrWhiteSpace(($existingBranch | Out-String).Trim())) {
        & git worktree add -b $BranchName $worktreePath $BaseBranch
    }
    else {
        & git worktree add $worktreePath $BranchName
    }

    if ($LASTEXITCODE -ne 0) {
        throw "git worktree add failed."
    }
}
finally {
    Pop-Location
}

$agentEnvPath = Join-Path $worktreePath ".env.agent"
$agentEnvLines = @(
    "# Generated by scripts/New-AgentWorkspace.ps1",
    "ASPNETCORE_ENVIRONMENT=Development",
    "ASPNETCORE_URLS=http://127.0.0.1:$HttpPort;https://127.0.0.1:$HttpsPort",
    "TELEMETRY_TRACKER_WORKSPACE_NAME=$Name",
    "TELEMETRY_TRACKER_BRANCH_NAME=$BranchName"
)
[System.IO.File]::WriteAllLines($agentEnvPath, $agentEnvLines)

$metadataPath = Join-Path $worktreePath ".agent-workspace.json"
$metadata = [ordered]@{
    name = $Name
    branchName = $BranchName
    baseBranch = $BaseBranch
    httpPort = $HttpPort
    httpsPort = $HttpsPort
    createdUtc = (Get-Date).ToUniversalTime().ToString("o")
}
$metadata | ConvertTo-Json | Set-Content -LiteralPath $metadataPath

$sourceEnvPath = Join-Path $repoRoot ".env"
$targetEnvPath = Join-Path $worktreePath ".env"
if ((Test-Path -LiteralPath $sourceEnvPath) -and -not (Test-Path -LiteralPath $targetEnvPath)) {
    Copy-Item -LiteralPath $sourceEnvPath -Destination $targetEnvPath
}

if (-not $SkipRestore) {
    Push-Location $worktreePath
    try {
        & dotnet restore telemetry-tracker.csproj
        if ($LASTEXITCODE -ne 0) {
            throw "dotnet restore failed for the new workspace."
        }
    }
    finally {
        Pop-Location
    }
}

Write-Host ("Created worktree: {0}" -f $worktreePath)
Write-Host ("Branch: {0}" -f $BranchName)
Write-Host ("HTTP port: {0}" -f $HttpPort)
Write-Host ("HTTPS port: {0}" -f $HttpsPort)
